import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { Plus, History, Search, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { ErrorBlock, LoadingBlock } from '@/components/StateBlock';
import { apiGet, apiPost } from '@/lib/api';
import { formatDate, formatIDR, getApiErrorMessage } from '@/lib/format';
import type { AccountsPayable, AccountsReceivable, Supplier } from '@/lib/types';
import { DebtPaymentDialog } from '@/components/DebtPaymentDialog';
import { printReceipt } from '@/lib/receipt';

export type DebtRow = AccountsPayable | AccountsReceivable;
const labels = { unpaid: 'Belum dibayar', partial: 'Sebagian dibayar', paid: 'Lunas', void: 'Retur / Void' };
export const partyName = (d: DebtRow) => 'customer_name' in d ? d.customer_name : d.supplier_name;

export default function DebtPage() {
  const [kind, setKind] = useState('receivables'), [status, setStatus] = useState('all'), [aging, setAging] = useState('all'), [search, setSearch] = useState(''), [page, setPage] = useState(1);
  const [payment, setPayment] = useState<DebtRow | null>(null), [history, setHistory] = useState<DebtRow | null>(null), [adding, setAdding] = useState(false);
  const client = useQueryClient();
  const query = useQuery({ queryKey: [kind], queryFn: () => apiGet<DebtRow[]>(`/${kind}`) });
  const suppliers = useQuery({ queryKey: ['suppliers'], queryFn: () => apiGet<Supplier[]>('/suppliers') });
  const system = useQuery({ queryKey: ['system'], queryFn: () => apiGet<{ today: string; timezone: string }>('/system') });
  const [form, setForm] = useState({ supplier_id: '', invoice_number: '', amount: '', due_date: '' });
  function refresh() { void client.invalidateQueries({ queryKey: ['receivables'] }); void client.invalidateQueries({ queryKey: ['payables'] }); void client.invalidateQueries({ queryKey: ['dashboard'] }); void client.invalidateQueries({ queryKey: ['excel-report'] }); void client.invalidateQueries({ queryKey: ['monthly-report'] }); }
  const create = useMutation({ mutationFn: () => apiPost('/payables', { ...form, amount: Number(form.amount) }), onSuccess: () => { toast.success('Hutang dicatat'); setAdding(false); setForm({ supplier_id: '', invoice_number: '', amount: '', due_date: '' }); refresh(); }, onError: e => toast.error(getApiErrorMessage(e)) });
  const rows = query.data ?? [];
  const active = rows.filter(d => ['unpaid', 'partial'].includes(d.status));
  const filtered = useMemo(() => rows.filter(d => (status === 'all' || d.status === status) && (aging === 'all' || d.aging_bucket === aging || (aging === 'upcoming' && d.days_remaining > 0)) && `${partyName(d)} ${d.invoice_number}`.toLowerCase().includes(search.toLowerCase())), [rows, status, aging, search]);
  const pages = Math.max(1, Math.ceil(filtered.length / 15)), current = Math.min(page, pages);
  return <div className="p-4 md:p-6 space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 data-testid="debt-page-title" className="font-heading text-2xl font-bold">Piutang & Hutang</h1><p data-testid="debt-page-description" className="text-sm text-muted-foreground">Terhubung ke checkout tempo dan stok masuk. Cicilan selalu tersimpan dalam riwayat.</p></div>{kind === 'payables' && <Button data-testid="add-payable-button" onClick={() => setAdding(true)}><Plus />Catat hutang</Button>}</header>
    <div className="flex gap-2"><Button data-testid="tab-receivables" variant={kind === 'receivables' ? 'default' : 'outline'} onClick={() => { setKind('receivables'); setPage(1); }}>Piutang pelanggan</Button><Button data-testid="tab-payables" variant={kind === 'payables' ? 'default' : 'outline'} onClick={() => { setKind('payables'); setPage(1); }}>Hutang distributor</Button></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[['Sisa aktif', active.reduce((s, d) => s+d.remaining, 0)], ['Terbayar (tanpa Void)', rows.filter(d => d.status !== 'void').reduce((s, d) => s+d.paid_amount, 0)], ['Lewat jatuh tempo', active.filter(d => d.days_overdue > 0).reduce((s, d) => s+d.remaining, 0)]].map(([title, amount], i) => <div className="bk-panel p-4" key={title} data-testid={`debt-summary-${i}`}><p className="text-sm text-muted-foreground">{title}</p><strong className="font-mono text-xl block mt-2">{formatIDR(Number(amount))}</strong></div>)}</div>
    <div className="bk-panel p-3 flex flex-wrap gap-2">{[['all', 'Semua umur'], ['upcoming', 'Belum jatuh tempo'], ['0-30', '0–30 hari'], ['31-60', '31–60 hari'], ['61-90', '61–90 hari'], ['90+', '>90 hari']].map(([value, label]) => <Button key={value} size="sm" variant={aging === value ? 'default' : 'outline'} data-testid={`aging-filter-${value}`} onClick={() => { setAging(value); setPage(1); }}>{label}<span className="text-xs opacity-70">{formatIDR(active.filter(d => value === 'all' || (value === 'upcoming' ? d.days_remaining > 0 : d.aging_bucket === value)).reduce((s, d) => s+d.remaining, 0))}</span></Button>)}</div>
    <div className="flex flex-wrap gap-3"><div className="relative flex-1 min-w-48"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" data-testid="debt-search" placeholder="Cari nama atau invoice…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div><select data-testid="debt-status-filter" aria-label="Filter status" className="bk-control max-w-48" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="all">Semua status</option>{Object.entries(labels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div>
    {query.isPending ? <LoadingBlock /> : query.isError ? <ErrorBlock error={query.error} onRetry={() => void query.refetch()} /> : <div className="bk-panel overflow-hidden"><div className="overflow-x-auto"><table className="bk-table"><thead><tr><th>Invoice / Nama</th><th>Total</th><th>Bayar</th><th>Sisa</th><th>Jatuh tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.slice((current-1)*15, current*15).map(d => <tr key={d.id} data-testid={`debt-row-${d.id}`}><td><b>{partyName(d)}</b><small>{d.invoice_number}</small></td><td data-testid={`debt-total-${d.id}`}>{formatIDR(d.amount)}</td><td data-testid={`debt-paid-${d.id}`}>{formatIDR(d.paid_amount)}</td><td data-testid={`debt-remaining-${d.id}`} className="font-semibold">{formatIDR(d.remaining)}</td><td><span>{formatDate(d.due_date)}</span><small className={d.days_overdue > 0 ? 'text-red-700 dark:text-red-400' : ''} data-testid={`debt-aging-${d.id}`}>{d.due_label}</small></td><td data-testid={`debt-status-${d.id}`}><span className={`bk-status ${d.status}`}>{labels[d.status]}</span></td><td><div className="flex gap-2"><Button variant="outline" size="icon-sm" aria-label="Riwayat pembayaran" data-testid={`history-${d.id}`} onClick={() => setHistory(d)}><History /></Button>{['unpaid', 'partial'].includes(d.status) && <Button size="sm" data-testid={`pay-${d.id}`} disabled={!system.data} onClick={() => setPayment(d)}>Bayar</Button>}</div></td></tr>)}</tbody></table></div>{filtered.length === 0 && <p data-testid="empty-debts" className="p-12 text-center text-muted-foreground">Belum ada tagihan yang cocok. Piutang dibuat melalui kasir tempo.</p>}<div className="flex justify-between items-center p-3 border-t border-border"><span data-testid="debt-pagination-info" className="text-xs text-muted-foreground">{filtered.length} tagihan · halaman {current}/{pages}</span><div className="flex gap-2"><Button size="sm" variant="outline" data-testid="debt-prev-page" disabled={current === 1} onClick={() => setPage(current-1)}>Sebelumnya</Button><Button size="sm" variant="outline" data-testid="debt-next-page" disabled={current === pages} onClick={() => setPage(current+1)}>Berikutnya</Button></div></div></div>}
    <p data-testid="aging-server-note" className="text-xs text-muted-foreground">Aging berdasarkan server {system.data?.today} ({system.data?.timezone}). 0–30 termasuk jatuh tempo hari ini; lunas dan Void tidak masuk aging.</p>
    {payment && system.data && <DebtPaymentDialog debt={payment} kind={kind} today={system.data.today} onClose={() => setPayment(null)} onSaved={refresh} />}
    <Dialog open={!!history} onOpenChange={o => !o && setHistory(null)}><DialogContent data-testid="payment-history-dialog"><DialogHeader><DialogTitle>Riwayat pembayaran</DialogTitle><DialogDescription>{history?.invoice_number} · {history && partyName(history)}</DialogDescription></DialogHeader>{history?.legacy_payment_history_missing && <p data-testid="legacy-payment-warning" className="bk-notice">Saldo terbayar berasal dari data lama; tanggal cicilan belum tersedia. Tidak dihitung sebagai penerimaan bulan ini.</p>}<div className="max-h-80 overflow-auto">{history?.payments.length ? history.payments.map((p, idx) => { const cum = history.payments.slice(0, idx + 1).reduce((s, x) => s + x.amount, 0); return <div key={p.id} data-testid={`payment-history-${p.id}`} className="flex justify-between items-center gap-4 border-b border-border py-3 text-sm"><div>{formatDate(p.payment_date)}<small className="block text-muted-foreground">{p.method} · {p.note}</small></div><div className="flex items-center gap-3"><b className="font-mono">{formatIDR(p.amount)}</b><Button variant="outline" size="icon-sm" aria-label="Cetak kwitansi" data-testid={`print-receipt-${p.id}`} onClick={() => printReceipt({ kind, party: partyName(history), debt: history, payment: p, cumulativePaid: cum })}><Printer /></Button></div></div>; }) : <p data-testid="no-payment-history" className="text-sm text-muted-foreground">Belum ada riwayat cicilan bertanggal.</p>}</div></DialogContent></Dialog>
    <Dialog open={adding} onOpenChange={setAdding}><DialogContent data-testid="payable-form-dialog"><DialogHeader><DialogTitle>Catat hutang distributor</DialogTitle><DialogDescription>Stok masuk sudah membuat hutang otomatis. Jangan catat invoice yang sama dua kali.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e => { e.preventDefault(); create.mutate(); }}><select className="bk-control" data-testid="payable-form-supplier-select" aria-label="Distributor" required value={form.supplier_id} onChange={e => setForm({ ...form, supplier_id: e.target.value })}><option value="">Pilih distributor</option>{suppliers.data?.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select><Input data-testid="payable-form-invoice-input" aria-label="Nomor invoice" placeholder="Nomor invoice" required value={form.invoice_number} onChange={e => setForm({ ...form, invoice_number: e.target.value })} /><Input data-testid="payable-form-amount-input" aria-label="Nominal hutang" type="number" min="0.01" max="1000000000000" step="0.01" placeholder="Nominal (Rp)" required value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} /><label className="block text-sm">Jatuh tempo<Input data-testid="payable-form-due-input" type="date" required value={form.due_date} onChange={e => setForm({ ...form, due_date: e.target.value })} /></label><Button data-testid="payable-form-submit-button" type="submit" disabled={create.isPending}>Simpan hutang</Button></form></DialogContent></Dialog>
  </div>;
}