import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { CheckCircle2, FileSpreadsheet, Upload, AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { ErrorBlock, LoadingBlock } from '@/components/StateBlock';
import { apiGet, apiPost } from '@/lib/api';
import { formatIDR, getApiErrorMessage } from '@/lib/format';

const GROUPS: Record<string,string> = { products: 'Produk & stok akhir', history: 'Riwayat transaksi + ledger', receivables: 'Saldo piutang', payables: 'Saldo hutang', reference: 'Snapshot laporan Agustus', purchases: 'Riwayat pembelian', transfers: 'Riwayat transfer', customers: 'Master pelanggan', suppliers: 'Master distributor', source_rows: 'Arsip seluruh sheet' };
type Preview = { digest: string; summary: Record<string, { total: number; ready: number; blocked: number; imported: boolean }>; warnings: string[]; checks: { month: string; differences: Record<string, number> }[]; rows: Record<string, any>[]; notice: string; filtered_total: number };

export default function ImportPage() {
  const [source, setSource] = useState('store_current'), [group, setGroup] = useState('products'), [page, setPage] = useState(1), [selected, setSelected] = useState<string[]>([]), [confirmed, setConfirmed] = useState(false);
  const client = useQueryClient();
  const [issuesOnly, setIssuesOnly] = useState(false);
  const query = useQuery({ queryKey: ['import-preview', source, group, page, issuesOnly], queryFn: () => apiGet<Preview>(`/imports/preview?source=${source}&group=${group}&page=${page}&issues_only=${issuesOnly}`) });
  const r = query.data;
  const commit = useMutation({ mutationFn: () => apiPost<{ results: Record<string, { status: string; count: number }> }>('/imports/commit', { source, digest: r?.digest, groups: selected, confirmed }), onSuccess: data => { const imported=Object.values(data.results).reduce((s, v) => s+(v.status === 'imported' ? v.count : 0), 0); toast.success(`${imported} catatan baru disimpan. Periksa kembali baris yang tertahan.`); setConfirmed(false); setSelected([]); void client.invalidateQueries(); }, onError: e => toast.error(getApiErrorMessage(e)) });
  const matched = r?.checks.every(c => Object.values(c.differences).every(n => Math.abs(n) <= 0.01));
  const totalPages = Math.max(1, Math.ceil((r?.filtered_total ?? 0)/20));
  return <div className="p-4 md:p-6 space-y-5"><header><span data-testid="import-eyebrow" className="text-xs text-primary tracking-widest">PEMERIKSAAN SEBELUM PENYIMPANAN</span><h1 data-testid="import-title" className="font-heading text-2xl font-bold mt-1">Impor Excel Perkasa Jaya</h1><p data-testid="import-description" className="text-sm text-muted-foreground mt-1">Periksa sumber spreadsheet dan status setiap kelompok. Data yang sudah diimpor tidak perlu dimasukkan ulang.</p></header><div className="flex flex-wrap gap-3"><select data-testid="import-source" aria-label="Sumber workbook" className="bk-control max-w-md" value={source} disabled={commit.isPending} onChange={e => { setSource(e.target.value); setSelected([]); setConfirmed(false); setPage(1); }}><option value="store_current">Store Information System ? file (1) terbaru</option><option value="store">Store Information System · file unik</option><option value="september">09 - Laporan Bulan September · isi Agustus 2026</option></select><Link to="/laporan-excel" data-testid="import-reconciliation-link" className="text-primary self-center text-sm">Lihat rekonsiliasi rumus →</Link></div>
    {query.isPending ? <LoadingBlock label="Membaca dan memeriksa workbook asli…" /> : query.isError ? <ErrorBlock error={query.error} onRetry={() => void query.refetch()} /> : r && <><div className="bk-notice flex items-start gap-3" data-testid="import-formula-status">{matched ? <CheckCircle2 className="size-5 text-emerald-700 dark:text-emerald-400 shrink-0" /> : <AlertTriangle className="size-5 text-red-700 dark:text-red-400 shrink-0" />}<span><b>{matched ? `${r.checks.length} periode cocok dengan hasil Excel` : 'Ada selisih rumus. Penyimpanan ditahan.'}</b><small className="block mt-1">Pemeriksaan ulang rumus, bukan sekadar menyalin angka akhir. File ganda tidak diproses dua kali.</small></span></div><div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-3">{Object.entries(r.summary).map(([key, s]) => <div key={key} className={`bk-panel p-4 ${group===key ? 'border-primary/60' : ''}`}><button data-testid={`import-group-${key}`} className="text-left w-full" onClick={() => { setGroup(key); setPage(1); }}><span className="text-xs text-muted-foreground">{GROUPS[key]}</span><strong className="font-heading text-2xl block my-2">{s.total.toLocaleString('id-ID')}</strong><span className="text-xs text-emerald-700 dark:text-emerald-400">{s.ready} lolos</span><span className="text-xs text-amber-700 dark:text-amber-400 ml-2">{s.blocked} ditahan</span></button><label className="mt-3 pt-3 border-t border-border text-xs flex gap-2 items-center"><input data-testid={`import-select-${key}`} type="checkbox" disabled={!s.ready || s.imported || commit.isPending} checked={selected.includes(key)} onChange={e => { setSelected(e.target.checked ? [...selected, key] : selected.filter(k => k !== key)); setConfirmed(false); }} /><span data-testid={`import-state-${key}`}>{s.imported ? 'Sudah diimpor' : s.ready ? 'Pilih baris lolos' : 'Perlu pemeriksaan'}</span></label></div>)}</div>
      <div className="bk-panel p-4 space-y-2" data-testid="import-warnings">{r.warnings.map((w, i) => <p key={w} data-testid={`import-warning-${i}`} className="text-xs text-muted-foreground leading-relaxed flex gap-2"><AlertTriangle className="size-3.5 text-amber-700 dark:text-amber-400 shrink-0 mt-0.5" />{w}</p>)}</div>
      <label className="flex items-center gap-2 text-sm"><input data-testid="import-issues-only" type="checkbox" checked={issuesOnly} onChange={e => { setIssuesOnly(e.target.checked); setPage(1); }} /><span data-testid="import-issues-label">Hanya tampilkan baris bermasalah</span></label>
      <section className="bk-panel overflow-hidden"><div className="p-4 flex gap-3 items-center border-b border-border"><FileSpreadsheet className="size-5 text-primary" /><h2 data-testid="import-table-title" className="font-heading text-lg">Pemeriksaan: {GROUPS[group]}</h2><span className="ml-auto text-xs text-muted-foreground" data-testid="import-row-count">{r.summary[group]?.total} baris</span></div><div className="overflow-x-auto"><table className="bk-table"><thead><tr><th>Sumber</th><th>Nama / invoice</th><th>Nilai / stok</th><th>Status pemeriksaan</th></tr></thead><tbody>{r.rows.map((row, i) => <tr key={`${row.sheet}-${row.row}-${i}`} data-testid={`import-row-${row.row}`}><td>{row.sheet}<small>Baris {row.row}</small></td><td>{row.name || row.party || row.month || 'Transaksi umum'}<small>{row.sku || row.invoice || row.date}</small>{group === 'products' && <small>Pemilik: {row.source_owner || row.owner || '?'} ? TAX: {row.tax ?? '?'} ? G: {row.source_stock_opening ?? '?'} ? Q: {row.source_stock_final ?? row.stock}</small>}</td><td>{group === 'products' ? `${row.stock} unit · ${formatIDR(row.selling_price)}` : row.amount !== undefined ? formatIDR(row.amount) : 'Snapshot rumus'}{row.remaining !== undefined && <small>Sisa {formatIDR(row.remaining)}</small>}</td><td className="max-w-md">{row.issue ? <span className="text-amber-700 dark:text-amber-400 text-xs">{row.issue}</span> : <span className="text-emerald-700 dark:text-emerald-400 text-xs">Lolos pemeriksaan</span>}{row.note && <small data-testid={`import-note-${row.row}`} className="block text-sky-700 dark:text-sky-400 text-xs mt-0.5">{row.note}</small>}</td></tr>)}</tbody></table></div>{!r.rows.length && <p className="p-8 text-center text-muted-foreground text-sm" data-testid="import-no-rows">Kelompok ini tidak tersedia pada workbook ini.</p>}<div className="p-3 flex justify-between items-center border-t border-border"><span className="text-xs text-muted-foreground" data-testid="import-page-number">Halaman {page}/{totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" data-testid="import-prev" disabled={page===1} onClick={() => setPage(page-1)}>Sebelumnya</Button><Button variant="outline" size="sm" data-testid="import-next" disabled={page>=totalPages} onClick={() => setPage(page+1)}>Berikutnya</Button></div></div></section>
      <section className="bk-panel p-5 space-y-4"><h2 className="font-heading text-lg" data-testid="import-confirmation-title">Simpan hanya setelah diperiksa</h2><label className="text-sm flex gap-3 items-start"><input data-testid="import-confirm-checkbox" type="checkbox" disabled={!selected.length || commit.isPending} checked={confirmed} onChange={e => setConfirmed(e.target.checked)} className="mt-1" /><span data-testid="import-confirmation-text">Saya sudah memeriksa sumber, periode, stok, dan baris tertahan. Saya menyetujui penyimpanan kelompok yang dipilih. Data yang sudah ada tidak ditimpa; transaksi historis tidak mengubah stok lagi.</span></label><Button data-testid="import-commit-button" disabled={!selected.length || !confirmed || !matched || commit.isPending || query.isFetching} onClick={() => commit.mutate()}><Upload />{commit.isPending ? 'Menyimpan, jangan tutup halaman…' : 'Impor kelompok yang disetujui'}</Button><p data-testid="import-notice" className="text-xs text-muted-foreground">{r.notice}</p></section>
      <p data-testid="xp-status-note" className="bk-notice">Versi ini adalah aplikasi web dengan database pada server aplikasi. Installer offline satu komputer Windows XP belum tersedia; runtime modern dari project ini tidak mendukung XP.</p>
    </>}
  </div>;
}